### ISSUE TITLE
Wifi Icon and Satus

### ISSUE THREAD

**Issue by Plabanm** [jldeen/bad-ass-terminal#1]
Hello

Thank you for your nice tutorial and codes for configuring Iterm2. I need your help to fix little issues I can not figure out how to fix.

On the top right corner, some information keeps coming up and I got them when I was setting up iTerms2 with powerline previously. This information repeateting as most of them coming on the bottom. 

On the bottom left corner, wifi icon is not showing.

<img width="1134" alt="screen shot 2017-11-13 at 14 02 17" src="https://user-images.githubusercontent.com/4824797/32729581-2f560876-c87c-11e7-91af-79dc66a6c5b2.png">

Please help me fix these. 

Thanks
Plaban

**Comment by Plabanm** [comment]
Another issue is full user@devicename coming on both top and bottom.

**Comment by Plabanm** [comment]
All problems seem to be solved by a restart of the mac but wifi icon still missing.

**Comment by jldeen** [comment]
Hi @Plabanm, Please ensure you are using the correct font. The wifi icon is part of the font in iTerm2.

**Comment by Plabanm** [comment]
@jldeen I am using the font suggested in your tutorial.
This line of code responsible for the icon.
`INTERNET=''`
this icon coming as the question mark and not quite readable in the code here.
Please help me correct it.

Thanks
